/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.firstteam1719.dashboard.testmode;

/**
 *
 * @author aaroneline
 */
public class JPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPanel
     */
    public JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        None = new javax.swing.JRadioButton();
        driveTest = new javax.swing.JRadioButton();
        otherTest = new javax.swing.JRadioButton();

        None.setText("None");
        None.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneActionPerformed(evt);
            }
        });

        driveTest.setText("Drive Test");
        driveTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driveTestActionPerformed(evt);
            }
        });

        otherTest.setText("Other Test");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(otherTest)
                    .add(driveTest)
                    .add(None))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(83, 83, 83)
                .add(None)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(driveTest)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(otherTest)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneActionPerformed
        // TODO add your handling code here:
        TestModeExtension.setNetworkTableNumber(0);
    }//GEN-LAST:event_NoneActionPerformed

    private void driveTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driveTestActionPerformed
        // TODO add your handling code here:
        TestModeExtension.setNetworkTableNumber(1);
    }//GEN-LAST:event_driveTestActionPerformed

    public void selectNone(boolean select){
        None.setSelected(select);
    }
    public void selectDrive(boolean select){
        driveTest.setSelected(select);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton None;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton driveTest;
    private javax.swing.JRadioButton otherTest;
    // End of variables declaration//GEN-END:variables
}
